[workspace]
resolver = "3"
members = ["matrix-mcp", "matrix-relay"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.104"
matrix-sdk = { version = "0.18.0", features = ["anyhow", "bundled-sqlite", "markdown"] }
secrecy = "0.10.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
clap = { version = "4.6.4", features = ["derive", "env"] }
clap-verbosity-flag = { version = "3.0.4", features = ["tracing"] }
